stages:
  - test
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  POSTGRES_DB: voiladb
  POSTGRES_USER: voila
  POSTGRES_PASSWORD: password
  PGDATA: "/var/lib/postgresql/data"
  POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
  MYSQL_DATABASE: voiladb
  MYSQL_ROOT_PASSWORD: password

test:
  image: openjdk:11-jdk
  stage: test
  services:
    - mysql:latest
  script:
    - cp $application_cicd_mysql_properties src/main/resources/application.properties
    - ./mvnw clean test
  except:
    - feature/gitlabci-config

publish_stage:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - cp $application_staging_mysql_properties src/main/resources/application.properties
    - docker build . -t $TAG_COMMIT -t $TAG_LATEST
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - master

deploy_stage:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f voila-backend || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --network=host -p 80:8080 --name voila-backend $TAG_COMMIT"
  environment:
    name: production
    url: http://213.232.11.195
  only:
    - master

deploy_k8s:
  stage: deploy
  image: matshareyourscript/aws-helm-kubectl
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  script:
    - kubectl config get-contexts
    - kubectl config use-context arn:aws:eks:eu-west-1:818879812205:cluster/voila-backend
    - kubectl get pods